### ISSUE TITLE
Installed all requirements with new pip but still has issue with BeautifulSoup

### ISSUE THREAD

**Issue by ElectricCaffeine** [aancw/Belati#10]
So I can't get Belati to work because it says:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-idn0rlbg/BeautifulSoup/
(during pip install)

...then I try to launch python Belati.py --help
and I get this:

            You are missing a module required for Belati. In order to continue using Belati, please install them with:
            `pip install -r requirements.txt`

            or manually install missing modules with:

            `pip install texttable python-geoip-geolite2 python-geoip dnsknife validators tqdm tldextract fake-useragent python-wappalyzer futures django`

Please help!

**Comment by 0xbadshah** [comment]
What's your output of `pip freeze` command ?

**Comment by ElectricCaffeine** [comment]
root@kali:~/Belati# pip freeze
Warning: cannot find svn location for chirp===daily-20170714
adns-python==1.2.1
AdvancedHTTPServer==2.0.10
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.22.0
attrs==17.2.0
Automat==0.6.0
backdoor-factory==0.0.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
billiard==3.3.0.23
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
brotlipy==0.6.0
bs4==0.0.1
capstone==3.0.4
certifi==2017.4.17
chardet==3.0.4
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170714
clearbit==0.1.4
click==6.7
colorama==0.3.7
config==0.3.9
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.9
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
decorator==4.1.1
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
Django==1.11.5
dnsknife==0.11
dnslib==0.9.7
dnspython==1.14.0
docutils==0.14
easygui==0.96
Elixir==0.7.1
enum34==1.1.6
fake-useragent==0.1.7
feedparser==5.1.3
Flask==0.12.2
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==3.1.1
GDAL==2.2.1
GeoIP==1.3.2
geoip2==2.5.0
geojson==2.3.0
gevent==1.1.2
google-api-python-client==1.6.3
greenlet==0.4.12
h2==2.5.2
hpack==3.0.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
hyperlink==17.3.1
icalendar==3.8
idna==2.1
impacket==0.9.15
incremental==16.10.1
ipaddr==2.2.0
ipaddress==1.0.17
ipwhois==0.15.1
IPy==0.83
ipython==5.1.0
ipython-genutils==0.2.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.9.6
jsbeautifier==1.6.4
json2html==1.0.1
jsonpickle==0.9.5
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.4.0
keyrings.alt==2.2
killerbee==1.0
lxml==3.8.0
M2Crypto==0.24.0
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.0.0
maxminddb==1.3.0
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.10
nassl==0.12
netaddr==0.7.18
NfSpy==1.0
numpy==1.13.1
oauth2client==4.1.2
olefile==0.44
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.1
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.3.0
pathtools==0.1.2
pcapy==0.10.8
pefile==2017.9.3
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
pluginbase==0.4
prettytable==0.7.2
prompt-toolkit==1.0.14
psycopg2==2.7.3
py==1.4.34
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
Pygments==2.2.0
pygobject==3.24.1
pygtkspellcheck==4.0.5
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.5.1
pymssql==2.1.3
pyOpenSSL==16.2.0
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.6
pyserial==3.4
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.2.1
python-bsonjs==0.2.0
python-dateutil==2.6.1
python-editor==0.4
python-geoip==1.2
python-geoip-geolite2==2015.303
python-Levenshtein==0.12.0
python-openid==2.2.5
python-pam==1.8.2
python-Wappalyzer==0.2.2
python-whois==0.6.5
pytz==2017.2
pyusb==1.0.0b2
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
requests==2.10.0
requests-file==1.4.2
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.4.2
scandir==1.5
scapy==2.3.3
scgi==1.13
SecretStorage==2.3.1
service-identity==16.0.0
Shapely==1.6.1
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.1.11
subprocess32==3.2.7
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
texttable==0.9.1
tldextract==2.1.0
tornado==4.5.1
tqdm==4.17.1
traitlets==4.3.2
Twisted==17.9.0rc1
typing==3.6.1
tzlocal==1.4
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.21.1
urwid==1.3.1
uTidylib==0.3
validators==0.12.0
vinetto==0.7b0
volatility==2.6
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.12.2.dev0
wfuzz==0.0.0
Whoosh==2.7.4
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.6.1
zenmap==7.60
zim==0.67
zope.interface==4.3.2

**Comment by 0xbadshah** [comment]
Try running `pip install -r requirements.txt` again.

**Comment by ElectricCaffeine** [comment]
I did that, but still same error. it's frustrating
Did you see that error message in my pip freeze output?

**Comment by 0xbadshah** [comment]
Which OS ? Python and pip version ?

**Comment by 0xbadshah** [comment]
Whats the output of the command `pip install -r requirements.txt` ?

**Comment by ElectricCaffeine** [comment]
Python version 2.7.13 and pip 9.0.1
(pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by aancw** [comment]
Hi, can you install manually for beautifulsoup4?

I think this is problem from beautifulsoup and your environment. Lemme know if this is still error.

**Comment by ElectricCaffeine** [comment]
No, that didn't help.
root@kali:~/Belati# pip install BeautifulSoup4
Requirement already satisfied: BeautifulSoup4 in /usr/local/lib/python2.7/dist-packages

root@kali:~/Belati# python Belati.py

            You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install -r requirements.txt`

            or manually install missing modules with:

            `pip install termcolor colorama future futures`

**Comment by aancw** [comment]
Nah, missing another dep. Just follow the guide.

**Comment by ElectricCaffeine** [comment]
No, man. The guide hasn't gotten me to where I need to be.. What else can i provide you that can assist in troubleshooting this issue? Thanks

**Comment by aancw** [comment]
This is your problem, right?

```
You are missing a module required for Belati. In order to continue using Belati, please install them with:

        `pip install -r requirements.txt`

        or manually install missing modules with:

        `pip install termcolor colorama future futures`
```

**Comment by aancw** [comment]
No problem with beautifulsoup again? Belati will check for missing dependency, because Belati can't run without needed dep. Can you try to clone and install in new folder? Sorry for this inconveniences :)

**Comment by ghost** [comment]
I still have this problem, but just with 'futures'. Could you help me?

> You are missing a module required for Belati. In order to continue using Belati, please install them with:

        `pip install -r requirements.txt`

        or manually install missing modules with:

        `pip install termcolor colorama future futures`

**Comment by aancw** [comment]
Hey @PowAd , you can look at this issue for futures problem https://github.com/aancw/Belati/issues/4

Fyi, Belati will provide a docker version so anyone can use in any environment :)

**Comment by aancw** [comment]
Hy, so many people have problems in this checker. As mentioned above, this is just because Belati not able to detect that plugins. I need to reproduce this issue in my environment. I'm using Arch Linux and Kali but no problem about deps.

This will be my todo -> https://github.com/aancw/Belati/issues/14

Hy @ElectricCaffeine , how about your problem?

**Comment by aancw** [comment]
Refer to closed issue https://github.com/aancw/Belati/issues/2

Can you uninstall and install that package again? Let me know if this is working

**Comment by aancw** [comment]
Hey. Can you run this command?

pip install --upgrade --force-reinstall packagename

**Comment by ElectricCaffeine** [comment]
still not working. I just did that command with BeautifulSoup4 as the packagename. The error still does not tell you which package is missing even after this command:
pip install dnspython requests termcolor colorama future beautifulsoup4 futures

the response was:
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages
Requirement already satisfied: termcolor in /usr/lib/python2.7/dist-packages
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages
Requirement already satisfied: future in /usr/lib/python2.7/dist-packages
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages
Requirement already satisfied: futures in /usr/lib/python2.7/dist-packages

**Comment by Chan9390** [comment]
Hey @ElectricCaffeine whats the output of `pip freeze` ?

**Comment by ElectricCaffeine** [comment]
@Chan9390 

root@kali:~/Belati# pip freeze
Warning: cannot find svn location for chirp===daily-20170714
adns-python==1.2.1
altgraph==0.14
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.22.0
attrs==17.2.0
Automat==0.6.0
backdoor-factory==0.0.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.6.0
billiard==3.3.0.23
BlindElephant==1.0
blinker==1.3
brotlipy==0.6.0
bs4==0.0.1
capstone==3.0.4
certifi==2017.4.17
chardet==3.0.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170714
clearbit==0.1.4
click==6.7
click-plugins==1.0.3
colorama==0.3.7
config==0.3.9
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.9
cssutils==1.0.2
cycler==0.10.0
decorator==4.1.1
dicttoxml==1.7.4
dis3==0.1.1
dissy==9
distorm3==3.3.4
Django==1.11.5
dnsknife==0.11
dnslib==0.9.7
dnspython==1.15.0
docutils==0.14
dropbox==8.2.0
easygui==0.96
EasyProcess==0.2.3
Elixir==0.7.1
enum34==1.1.6
fake-useragent==0.1.7
feedparser==5.1.3
Flask==0.12.2
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.15.2
futures==3.1.1
fuzzywuzzy==0.15.1
GDAL==2.2.1
GeoIP==1.3.2
gevent==1.2.2
gitdb2==2.0.3
GitPython==2.1.7
google-api-python-client==1.6.3
greenlet==0.4.12
h2==2.5.2
hpack==3.0.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
hyperlink==17.3.1
idna==2.5
impacket==0.9.15
incremental==16.10.1
ipaddr==2.2.0
ipaddress==1.0.17
iptools==0.6.1
ipwhois==0.15.1
IPy==0.83
ipython==5.1.0
ipython-genutils==0.2.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.9.6
jsbeautifier==1.6.4
json2html==1.0.1
jsonpickle==0.9.5
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.4.0
keyrings.alt==2.2
killerbee==1.0
lxml==4.0.0
M2Crypto==0.24.0
macholib==1.8
Mako==1.0.7
MarkupSafe==1.0
matplotlib==2.0.0
mechanize==0.2.5
mercurial==4.3.1
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.10
nassl==0.12
netaddr==0.7.18
netifaces==0.10.6
NfSpy==1.0
numpy==1.13.1
oauth2client==4.1.2
oauthlib==2.0.4
olefile==0.44
openpyxl==2.3.0
PAM==0.4.2
paramiko==2.0.0
passlib==1.7.1
pathlib2==2.3.0
pathtools==0.1.2
pcapy==0.10.8
pefile==2017.9.3
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.2.1
prettytable==0.7.2
prompt-toolkit==1.0.14
psycopg2==2.7.3
py==1.4.34
pyasn1==0.1.9
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycurl==7.43.0
PyDispatcher==2.0.5
pydns==2.3.6
pyenchant==1.6.7
Pygments==2.2.0
pygobject==3.24.1
pygraphviz==1.4rc1
pygtkspellcheck==4.0.5
pyinotify==0.9.6
PyInstaller==3.3
pylibemu==0.3.3
pymongo==3.5.1
pymssql==2.1.3
pyOpenSSL==16.2.0
pyparsing==2.1.10
pyPdf==1.13
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.6
pyserial==3.4
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.2.1
python-bsonjs==0.2.0
python-dateutil==2.6.1
python-geoip==1.2
python-geoip-geolite2==2015.303
python-Levenshtein==0.12.0
python-qt-binding==0.2.17
python-Wappalyzer==0.2.2
python-whois==0.6.5
pytz==2017.2
pyusb==1.0.0b2
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
qt4reactor==1.6
rdpy==1.3.2
requests==2.18.1
requests-file==1.4.2
requests-oauthlib==0.8.0
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.4.2
scandir==1.5
scapy==2.3.3
SecretStorage==2.3.1
selenium==3.6.0
service-identity==16.0.0
Shapely==1.6.1
shodan==1.7.5
simplegeneric==0.8.1
simplejson==3.11.1
singledispatch==3.4.0.3
six==1.11.0
slowaes==0.1a1
smmap2==2.0.3
socketpool==0.5.3
SQLAlchemy==1.1.11
subprocess32==3.2.7
tcpwatch==1.3.1
termcolor==1.1.0
texttable==0.9.1
tldextract==2.1.0
tornado==4.5.1
tqdm==4.17.1
traitlets==4.3.2
tweepy==3.5.0
Twisted==17.9.0
typing==3.6.1
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.21.1
urwid==1.3.1
uTidylib==0.3
validators==0.12.0
vinetto==0.7b0
volatility==2.6
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.12.2.dev0
wfuzz==0.0.0
Whoosh==2.7.4
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.6.1
zenmap==7.60
zim==0.67
zlib-wrapper==0.1.3
zope.interface==4.3.2
root@kali:~/Belati#

**Comment by aancw** [comment]
@ElectricCaffeine  Use this parameter

pip install --upgrade --force-reinstall dnspython requests termcolor colorama future beautifulsoup4 futures

Let me know if this is working

**Comment by ElectricCaffeine** [comment]
Unfortunately not. With that command, it installed some more things but still generated the same error. These are what it said was not installed:

root@kali:~/Belati# pip install --upgrade --force-reinstall dnspython requests termcolor colorama future beautifulsoup4 futures
Collecting dnspython
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 1.3MB/s 
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.7MB/s 
Collecting termcolor
  Downloading termcolor-1.1.0.tar.gz
Collecting colorama
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting future
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.1MB/s 
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.6.0-py2-none-any.whl
Collecting futures
  Downloading futures-3.1.1-py2-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 3.5MB/s 
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.4MB/s 
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 2.5MB/s 
Building wheels for collected packages: termcolor, future
  Running setup.py bdist_wheel for termcolor ... done
  Stored in directory: /root/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built termcolor future
Installing collected packages: dnspython, urllib3, idna, chardet, certifi, requests, termcolor, colorama, future, beautifulsoup4, futures
  Found existing installation: dnspython 1.15.0
    Not uninstalling dnspython at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: urllib3 1.21.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: idna 2.5
    Not uninstalling idna at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: chardet 3.0.4
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: certifi 2017.4.17
    Not uninstalling certifi at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: requests 2.18.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: termcolor 1.1.0
    Not uninstalling termcolor at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: colorama 0.3.7
    Not uninstalling colorama at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: future 0.15.2
    Not uninstalling future at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: beautifulsoup4 4.6.0
    Not uninstalling beautifulsoup4 at /usr/lib/python2.7/dist-packages, outside environment /usr
  Found existing installation: futures 3.1.1
    Not uninstalling futures at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed beautifulsoup4-4.6.0 certifi-2017.7.27.1 chardet-3.0.4 colorama-0.3.9 dnspython-1.15.0 future-0.16.0 futures-3.1.1 idna-2.6 requests-2.18.4 termcolor-1.1.0 urllib3-1.22

root@kali:~/Belati# python Belati.py 

            You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install -r requirements.txt`

            or manually install missing modules with:

            `pip install dnspython requests termcolor colorama future beautifulsoup4 futures`

            
root@kali:~/Belati#

**Comment by aancw** [comment]
Hm... Strange issue. I'm not facing that problem when using Kali2. No idea what's wrong with your python environment. Maybe you need to wait for docker version.

**Comment by ElectricCaffeine** [comment]
Hmm..any way to reset the Python environment? yours is working fine in Kali?

**Comment by 0xbadshah** [comment]
I would suggest using virtualenv. Try executing the following commands:
```bash
virtualenv belati
source belati/bin/activate # if you are using other terminals like fish, use activate.fish
pip install -r requirements.txt
# after using the tool you could just execute the following command to exit
deactivate
```

**Comment by ElectricCaffeine** [comment]
Thanks! more progress, but another stopping point:

(Belati) root@kali:~/Belati# python Belati.py
Traceback (most recent call last):
  File "Belati.py", line 56, in <module>
    from lib.CheckMyUsername.check_my_username import CheckMyUsername
ImportError: No module named CheckMyUsername.check_my_username
(Belati) root@kali:~/Belati#

**Comment by aancw** [comment]
Belati running well on my Kali2 VM.

Git checkout submodule first for this problem:
lib.CheckMyUsername.check_my_username 

Your problem is solved?
