### ISSUE TITLE
Investigating Missing Dependency Checker

### ISSUE THREAD

**Issue by aancw** [aancw/Belati#14]
I need to investigate this issue. Some people have problems in dependency checker.

**Comment by 0xbadshah** [comment]
When you install python using `apt-get install python`, so many other python packages like `python-bs4`, `python-idna` gets installed by default. (This version comes pre-installed in Kali too) These packages are required by Belati but are not installed using pip. Doing a `pip install beautifulsoup4` will not replace the original package (as a package with that name is already present).

So when you execute the command in https://github.com/aancw/Belati/blob/master/plugins/dep_check.py#L58, there is a list which shows all the dependencies along with the required packages installed, but fails to see the correct version.

The solution: Either use 1 or 2
1) **Change the command in `dep_check.py`**
2) **Remove the default packages: `apt-get remove -y --purge python-bs4 python-idna python-chardet`** and then execute `pip install -r requirements`

**Comment by aancw** [comment]
I think this is just because package not installed after upgrading or system cache. I've already provide guide for this. Closed this issue.
