### ISSUE TITLE
python setup.py egg_info failed

### ISSUE THREAD

**Issue by attacker34** [aancw/Belati#15]
Dear ,
When i used the command to pip install -r requirements.txt 
I got the error at the processing of the command.

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Ty_TXr/pyexifinfo/

```

how can i fix it?

**Comment by aancw** [comment]
Install exiftool first.

**Comment by aancw** [comment]
Refer to this issue: 

https://github.com/guinslym/pyexifinfo/issues/9

**Comment by attacker34** [comment]
@aancw  Thanks for quick response.i tried pip install exiftool but it failed with this message:

```
pip install exiftool
Collecting exiftool
  Could not find a version that satisfies the requirement exiftool (from versions: )
No matching distribution found for exiftool

```

**Comment by aancw** [comment]
Not that. I mean exiftool package for your distro. Just like this : apt-get install exiftool

**Comment by attacker34** [comment]
Thanks , all things have been installed but when i tried to run command for help

```
python Belati.py --help
Traceback (most recent call last):
  File "Belati.py", line 43, in <module>
    from plugins.gather_company import GatherCompany
  File "/root/pentest/Belati/plugins/gather_company.py", line 24, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**Comment by aancw** [comment]
Hm... bs4? How about installing beautifulsoup4

pip install beautifulsoup4

**Comment by aancw** [comment]
or pip install --upgrade --force-reinstall beautifulsoup4

**Comment by attacker34** [comment]
pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages

**Comment by aancw** [comment]
Hm.. strange issue. Let me check and run in fresh install system.

**Comment by 0xbadshah** [comment]
Hey @attacker420 did you try executing `pip install --upgrade --force-reinstall beautifulsoup4`.

**Comment by 0xbadshah** [comment]
Whats the output of `pip freeze` ?

**Comment by attacker34** [comment]
pip freeze
Warning: cannot find svn location for chirp===daily-20170124
adns-python==1.2.1
AdvancedHTTPServer==2.0.9
alembic==0.8.8.dev0
anyjson==0.3.3
argcomplete==1.8.1
argh==0.26.2
attrs==16.3.0
awscli==1.11.158
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
basemap==1.0.7
BBQSQL==1.0
BeautifulSoup==3.2.1
beautifulsoup4==4.4.1
bfac==1.3
billiard==3.3.0.23
BlindElephant==1.0
blinker==1.3
boltons==16.4.1
botocore==1.7.16
brotlipy==0.6.0
bs4==0.0.1
capstone==3.0.4
certifi==2016.2.28
chardet==2.3.0
Cheetah==2.4.4
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20170124
chrome-gnome-shell==0.0.0
clearbit==0.1.4
click==6.6
colorama==0.3.9
config==0.3.9
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.3.0.post2
constantly==15.1.0
construct==2.5.2
couchdbkit==0.6.5
cryptography==1.7.1
cssutils==1.0
cycler==0.10.0
dap==2.2.6.7
DateTime==4.2
decorator==4.0.11
dicttoxml==1.7.4
dissy==9
distorm3==3.3.4
Django==1.11.6
dnsknife==0.11
dnspython==1.15.0
docutils==0.13.1
easygui==0.96
EasyProcess==0.2.3
Elixir==0.7.1
enum34==1.1.6
fake-useragent==0.1.7
feedparser==5.1.3
Flask==0.12
FormEncode==1.3.0
functools32==3.2.3.post2
fuse-python==0.2.1
future==0.16.0
futures==3.1.1
fuzzywuzzy==0.15.1
GDAL==2.1.2
GeoIP==1.3.2
geoip2==2.4.2
geojson==1.3.1
gevent==1.1.2
google==1.9.3
google-api-python-client==1.6.3
greenlet==0.4.11
h2==2.5.2
hpack==2.3.0
html2text==2016.9.19
html5lib==0.999999999
http-parser==0.8.3
httplib2==0.9.2
httpretty==0.8.14
hyperframe==4.0.1
icalendar==3.8
idna==2.1
impacket==0.9.15
incremental==16.10.1
ipaddr==2.2.0
ipaddress==1.0.17
ipwhois==0.15.1
IPy==0.83
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
jdcal==1.0
Jinja2==2.8
jmespath==0.9.3
jsbeautifier==1.6.4
json2html==1.0.1
jsonpickle==0.9.3
jsonrpclib==0.1.3
keepnote==0.7.8
keyring==10.1
keyrings.alt==1.3
killerbee==1.0
knockpy==4.1.1
lxml==3.7.1
M2Crypto==0.24.0
Mako==1.0.6
MarkupSafe==0.23
matplotlib==2.0.0
maxminddb==1.2.3
mechanize==0.2.5
mercurial==4.0
metaconfig==0.1.4a1
mitmproxy==0.18.2
mockito==0.5.2
msgpack-python==0.4.8
mysqlclient==1.3.7
nassl==0.12
netaddr==0.7.18
NfSpy==1.0
numpy==1.12.0
oauth2client==4.1.2
olefile==0.42.1
openpyxl==2.3.0
PAM==0.4.2
pandas==0.19.2
paramiko==2.0.0
passlib==1.7.0.post20161128115349
Paste==2.0.3
PasteDeploy==1.5.2
PasteScript==1.7.5
pathlib2==2.1.0
pathtools==0.1.2
pcapy==0.10.8
pefile==2016.3.28
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
pluginbase==0.4
prettytable==0.7.2
progressbar==2.3
prompt-toolkit==1.0.9
psycopg2==2.6.2
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.3.6
pyasn1-modules==0.0.7
pycrypto==2.6.1
pycurl==7.43.0
pydns==2.3.6
pyenchant==1.6.7
pyexifinfo==0.4.0
Pygments==2.2.0
pygobject==3.22.0
pygtkspellcheck==4.0.5
pyinotify==0.9.6
pylibemu==0.3.3
pymongo==3.4.0
pymssql==1.0.2
pyOpenSSL==16.2.0
pyotp==2.2.1
pyparsing==2.1.10
PyPDF2==1.26.0
pyperclip==1.5.27
pyrit==0.5.1
pyscard==1.9.4
pyserial==3.2.1
pysnmp==4.3.2
pysnmp-apps==0.3.2
pysnmp-mibs==0.1.3
PySocks==1.6.5
pyspatialite==3.0.1
pysqlite==2.7.0
pytest==3.0.6
python-dateutil==2.5.3
python-editor==0.4
python-geoip==1.2
python-geoip-geolite2==2015.303
python-Levenshtein==0.12.0
python-openid==2.2.5
python-pam==1.8.2
python-Wappalyzer==0.2.2
python-whois==0.6.5
pytz==2016.7
pyusb==1.0.0b2
PyVirtualDisplay==0.2.1
PyX==0.12.1
pyxdg==0.25
PyYAML==3.12
qrcode==5.3
qt4reactor==1.6
rdpy==1.3.2
requests==2.10.0
requests-file==1.4.2
restkit==4.2.2
rfidiot==1.0
roman==2.0.0
rsa==3.4.2
s3transfer==0.1.11
scapy===unknown.version
scgi==1.13
SecretStorage==2.3.1
selenium==3.5.0
service-identity==16.0.0
Shapely==1.5.17
simplegeneric==0.8.1
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.10.0
slowaes==0.1a1
smoke-zephyr==1.0.2
socketpool==0.5.3
SQLAlchemy==1.0.15
subprocess32==3.2.7
tabulate==0.8.1
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
terminaltables==3.1.0
texttable==0.9.1
tldextract==2.1.0
tornado==4.4.2
tqdm==4.19.2
traitlets==4.3.1
Twisted==16.6.0
typing==3.5.2.2
tzlocal==1.3
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.20
urwid==1.3.1
uTidylib==0.3
validators==0.12.0
vinetto==0.7b0
volatility==2.6
wafw00f==0.9.3
wapiti==2.3.0
watchdog==0.8.3
wcwidth==0.1.7
webencodings==0.5
webunit==1.3.10
Werkzeug==0.11.15
wfuzz==0.0.0
Whoosh==2.7.0
wxPython==3.0.2.0
wxPython-common==3.0.2.0
XlsxWriter==0.9.6
xmlbuilder==1.0
yara-python==3.5.0
zenmap==7.40
zim==0.65
zope.interface==4.3.2

**Comment by attacker34** [comment]
is anything missing? check the pip

**Comment by 0xbadshah** [comment]
Everything looks fine in the output.

**Comment by psychomad** [comment]
Hi all
Same prob for me everything was fine. but strange this

Collecting BeautifulSoup==3.2.1 (from python-wappalyzer->-r requirements.txt (line 14))
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-col9wtcu/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-col9wtcu/BeautifulSoup/

I tried to install wappalyzer-python in a separate shell and everything was fine.. then launch requirements install and still the problem...
I try to remove BeautifulSoup4 and wappalyzer-python from requirements and everything reach the end fine, then start Belati and still no work... (just to try)

**Comment by aancw** [comment]
Hy psychomad, for bs4 you need to install c++ dev first. Like gcc and other package. See instructions for Fedora section in readme

**Comment by aancw** [comment]
Hy @psychomad , not BeautifulSoup but beautifulsoup4. That's different package :)

**Comment by R3dFruitRollUp** [comment]
Same problem with the egg

ec2-user@kali:~/Belati$ pip install --upgrade --force-reinstall -r requirements.txt
Collecting dnspython (from -r requirements.txt (line 1))
  Downloading dnspython-1.15.0-py2.py3-none-any.whl (177kB)
    100% |████████████████████████████████| 184kB 3.0MB/s
Collecting requests (from -r requirements.txt (line 2))
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 4.0MB/s
Collecting argparse (from -r requirements.txt (line 3))
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Collecting texttable (from -r requirements.txt (line 4))
  Downloading texttable-1.1.1.tar.gz
Collecting python-geoip-geolite2 (from -r requirements.txt (line 5))
  Downloading python_geoip_geolite2-2015.0303-py2-none-any.whl (17.2MB)
    100% |████████████████████████████████| 17.2MB 73kB/s
Collecting python-geoip (from -r requirements.txt (line 6))
  Downloading python_geoip-1.2-py27-none-any.whl
Collecting dnsknife (from -r requirements.txt (line 7))
  Downloading dnsknife-0.11.tar.gz
Collecting termcolor (from -r requirements.txt (line 8))
  Downloading termcolor-1.1.0.tar.gz
Collecting colorama (from -r requirements.txt (line 9))
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting validators (from -r requirements.txt (line 10))
  Downloading validators-0.12.0.tar.gz
Collecting tqdm (from -r requirements.txt (line 11))
  Downloading tqdm-4.19.4-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 6.4MB/s
Collecting tldextract (from -r requirements.txt (line 12))
  Downloading tldextract-2.2.0-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 11.5MB/s
Collecting fake-useragent (from -r requirements.txt (line 13))
  Downloading fake-useragent-0.1.8.tar.gz
Collecting python-wappalyzer (from -r requirements.txt (line 14))
  Downloading python-Wappalyzer-0.2.2.tar.gz
Collecting future (from -r requirements.txt (line 15))
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 1.6MB/s
Collecting beautifulsoup4 (from -r requirements.txt (line 16))
  Downloading beautifulsoup4-4.6.0-py2-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 10.8MB/s
Collecting python-whois (from -r requirements.txt (line 17))
  Downloading python-whois-0.6.5.tar.gz
Collecting futures (from -r requirements.txt (line 18))
  Downloading futures-3.1.1-py2-none-any.whl
Collecting django (from -r requirements.txt (line 19))
  Downloading Django-1.11.7-py2.py3-none-any.whl (6.9MB)
    100% |████████████████████████████████| 7.0MB 196kB/s
Collecting pyexifinfo (from -r requirements.txt (line 20))
  Downloading pyexifinfo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pyexifinfo.egg-info
    writing pip-egg-info/pyexifinfo.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pyexifinfo.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pyexifinfo.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/pyexifinfo.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Muq6VH/pyexifinfo/setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "/tmp/pip-build-Muq6VH/pyexifinfo/setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "/usr/lib/python2.7/subprocess.py", line 168, in call
        return Popen(*popenargs, **kwargs).wait()
      File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child        raise child_exception
    OSError: [Errno 2] No such file or directory

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Muq6VH/pyexifinfo



Any assistance?

kali linux AMI on aws

**Comment by aancw** [comment]
Please install exiftool

**Comment by irwandi** [comment]
> chroot:Belati irwandi$ sudo -H pip install django
> Collecting django
>   Downloading Django-2.0.tar.gz (8.0MB)
>     100% |████████████████████████████████| 8.0MB 116kB/s
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-wjO4nj/django/setup.py", line 32, in <module>
>         version = __import__('django').get_version()
>       File "django/__init__.py", line 1, in <module>
>         from django.utils.version import get_version
>       File "django/utils/version.py", line 61, in <module>
>         @functools.lru_cache()
>     AttributeError: 'module' object has no attribute 'lru_cache'

lru_cache only available in python3

CMIIW

**Comment by aancw** [comment]
@irwandi Please use Django with version (1.11). 

Reference:
https://stackoverflow.com/questions/42196124/there-are-errors-when-i-install-django-by-git

**Comment by aancw** [comment]
This is Django version table from official website:

![django-version](https://user-images.githubusercontent.com/6284204/34815100-aeb59a2a-f6e2-11e7-87cb-0f726e844e4d.png)

**Comment by sil3nt-4unt3r** [comment]
Hello I m trying to install Belati to my ubuntu17.10 and got error  so how to solve this error ??

Traceback (most recent call last):
  File "./Belati.py", line 26, in <module>
    dep_check.check_dependency()
  File "/root/Downloads/gitsoft/Belati/plugins/dep_check.py", line 58, in check_dependency
    pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
AttributeError: 'module' object has no attribute 'get_installed_distributions'

this is my pip freeze result

apturl==0.5.2
asn1crypto==0.22.0
attrs==18.1.0
Automat==0.6.0
beautifulsoup4==4.6.0
Brlapi==0.6.5
certifi==2017.4.17
chardet==3.0.4
clearbit==0.1.7
click==6.2
command-not-found==0.3
config==0.3.9
configobj==5.0.6
constantly==15.1.0
cryptography==1.9
cupshelpers==1.0
Cython==0.28.2
defer==1.0.6
distro-info==0.17
Django==1.11
dnspython==1.15.0
ez-setup==0.9
future==0.16.0
gfm==0.0.3
google-api-python-client==1.6.7
html2text==2015.11.4
html5lib==0.999999999
httplib2==0.9.2
hyperlink==18.0.0
idna==2.5
incremental==17.5.0
ipwhois==1.0.0
Jinja2==2.8
json2html==1.2.1
keyring==10.4.0
keyrings.alt==2.2
language-selector==0.1
launchpadlib==1.10.5
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.0.0
lxml==4.2.1
Mako==1.0.7
Markdown==2.6.5
MarkupSafe==1.0
more-itertools==4.1.0
netaddr==0.7.19
numpy==1.14.3
oauth==1.0.1
oauth2client==4.1.2
oauthlib==2.0.7
olefile==0.44
pbr==4.0.2
pexpect==4.2.1
Pillow==4.1.1
piplapis-python==5.1.4
pluggy==0.6.0
praw==5.4.0
prawcore==0.14.0
py==1.5.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
pycups==1.9.73
pygobject==3.24.1
pymongo==3.6.1
PyRSS2Gen==1.1
PySocks==1.6.8
pystan==2.17.1.0
pytest==3.5.1
pytest-rerunfailures==4.0
python-apt==1.4.0b3
python-dateutil==2.7.2
python-debian==0.1.30
python-whois==0.7.0
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
reportlab==3.4.0
requests==2.18.4
requests-file==1.4.3
requests-oauthlib==0.8.0
rsa==3.4.2
SecretStorage==2.3.1
simplejson==3.11.1
six==1.10.0
system-service==0.3
systemd-python==234
termcolor==1.1.0
testresources==2.0.1
tld==0.7.10
tldextract==2.2.0
tqdm==4.23.2
TravisPy==0.3.5
tweepy==3.6.0
ubuntu-drivers-common==0.0.0
ufw==0.35
unattended-upgrades==0.1
update-checker==0.16
uritemplate==3.0.0
urllib3==1.22
usb-creator==0.3.3
vboxapi==1.0
wadllib==1.3.2
webencodings==0.5
xkit==0.0.0
zope.interface==4.5.0
 please help
