### ISSUE TITLE
Sublist3r error

### ISSUE THREAD

**Issue by 0xbadshah** [aancw/Belati#18]
### Host System

- OS : Debian 9
- Python version (`python --version`) : Python 2.7.13
- Pip version (`pip --version`) : pip 9.0.1 from /usr/lib/python2.7/dist-packages
- Output of `pip freeze` : -

### Error Description

If I run Belati with some `domain.com`, I would get `older.sublist3r.versions.work.better.for.domain.com` as a subdomain. This affects the further activities of the tool like wapplyzing and finding Git and SVN repos in the above mentioned non-existing subdomain. The error has been resolved in the project's master branch but has not been updated in Belati.

Checkout https://github.com/aboul3la/Sublist3r/issues/86 for more details.

**Comment by aancw** [comment]
Exactly. This is issue because sublist3r blocked by passive dns. I need updating sublist3r source source to spesific version before latest version.

**Comment by aancw** [comment]
Not using sublist3r anymore.
