### ISSUE TITLE
Strange

### ISSUE THREAD

**Issue by psychomad** [aancw/Belati#2]
Hello
I have this problem, or just i'm sooo noob and i can't see the mistake.. i use pip v2 and python v2 to do all as you request... i have all in order but..

root@Plague:/home/docplague/Scrivania/arsenale/Belati# pip install dnspython termcolor colorama
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages
Requirement already satisfied: termcolor in /usr/lib/python2.7/dist-packages
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages
root@Plague:/home/docplague/Scrivania/arsenale/Belati# pip2 install dnspython
Requirement already satisfied: dnspython in /usr/lib/python2.7/dist-packages
root@Plague:/home/docplague/Scrivania/arsenale/Belati# pip2 install colorama
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages
root@Plague:/home/docplague/Scrivania/arsenale/Belati# python Belati.py -h

            You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install -r requirements.txt`

            or manually install missing modules with:

            `pip install dnspython termcolor colorama`

Any hint?

**Comment by aancw** [comment]
Hi, `pip` is just standart for default python system. If you have multiple python version, please use `pip` which associated to python v2. For me, this will work:

```
pip2 install -r requirements.txt
```

And try running with python v2 binary. For me:

```
python2 Belati.py -h
```

Can you provide the output from this command `python -V && pip -V` and `pip install -r requirements.txt` ?

I have added Missing Dependency Checker. What is your operating system? Maybe i can test and reproduce this issue.

**Comment by psychomad** [comment]
Hi
Exactly what i did. I have different version of python for different needs and i always use the python2 python3 or pip2 or pip3 it depends what i need.
Just to be sure i follow your instruction:

i# pip2 install -r requireme                                                                                        nts.txt
Requirement already satisfied: dnspython in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 3))
Requirement already satisfied: texttable in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: python-geoip-geolite2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: python-geoip in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: dnsknife in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: termcolor in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: colorama in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: validators in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: tldextract in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: fake-useragent in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: python-wappalyzer in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from dnsknife->-r requirements.txt (line 7))
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from dnsknife->-r requirements.txt (line 7))
Requirement already satisfied: decorator>=3.4.0 in /usr/lib/python2.7/dist-packages (from validators->-r requirements.txt (line 10))
Requirement already satisfied: idna in /usr/local/lib/python2.7/dist-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: requests-file>=1.4 in /usr/local/lib/python2.7/dist-packages (from tldextract->-r requirements.txt (line 12))
Requirement already satisfied: BeautifulSoup==3.2.1 in /usr/lib/python2.7/dist-packages (from python-wappalyzer->-r requirements.txt (line 14))
root@Plague:/home/docplague/Scrivania/arsenale/Belati# python2 Belati.py -h

            You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install -r requirements.txt`

            or manually install missing modules with:

            `pip install termcolor colorama`

And still even if they are satisfy... when i start Belati.. it asked me (sorry for my english)

**Comment by aancw** [comment]
When you are using `pip2 install -r requirements.txt` no output error?

I've just try this with CentOS and work as well. What OS you are using?

Maybe this issue caused by 

```pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])``` that termcolor and colorama not in list. You can check installed pip package with this:

```
[root@localhost BELATI]# python2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip
>>> pip_list = sorted([(i.key) for i in pip.get_installed_distributions()])
>>> print(pip_list)
```

**Comment by psychomad** [comment]
Im using Kali 2016 updated.
No error using pip2

Seem you right:
['beautifulsoup4', 'billiard', 'bs4', 'cement', 'clearbit', 'click-plugins', 'co          nfig', 'cymon', 'cython', 'dnsknife', 'dnspython', 'droopescan', 'fake-useragent', 'gevent', 'ghost.py', 'google-api-python-client', 'greenlet', 'idna', 'inquis          itor', 'ipwhois', 'json2html', 'nassl', 'nose', 'oauth2client', 'oauthlib', 'par          se', 'pyinstaller', 'pystache', 'python-geoip', 'python-geoip-geolite2', 'python -wappalyzer', 'python-whois', 'pythonwhois', 'pyzmq', 'recordtype', 'requests', 'requests-file', 'requests-oauthlib', 'rsa', 'sh', 'shodan', 'simplejson', 'sslyze', 'tabulate', 'texttable', 'thready', 'tld', 'tldextract', 'tqdm', 'tweepy',  'unidecode', 'unqlite', 'uritemplate', 'urlparse2', 'urlparse3', 'urlparse4', 'validate-email', 'validators', 'websocket']
So i try to : pip2 install termcolor and colorama?

**Comment by aancw** [comment]
From your output, termcolor and colorama is not installed. Try to reinstall that package if already installed.

```
pip2 uninstall termcolor colorama
pip2 install termcolor colorama
```

**Comment by psychomad** [comment]
Thanks but....
when i try to uninstall:

Not uninstalling colorama at /usr/lib/python2.7/dist-packages, outside environment /usr

any hint?

**Comment by aancw** [comment]
Hm... You will be seeing this message when uninstalling pip package:

```
[root@KotakRusak BELATI]# pip2 uninstall termcolor colorama
DEPRECATION: Uninstalling a distutils installed project (termcolor) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
Uninstalling termcolor-1.1.0:
  /usr/lib/python2.7/site-packages/termcolor-1.1.0-py2.7.egg-info
Proceed (y/n)? 
```

**Comment by psychomad** [comment]
No just what i paste.. nothing else for this i can't understand.. im try to googlein to understand what's going on

**Comment by aancw** [comment]
Try to upgrade your pip version?

```
pip2 install --upgrade pip
```


Look at this:

https://github.com/byt3bl33d3r/MITMf/issues/308

**Comment by psychomad** [comment]
Did and i found the same, possibly bug.
result: it worked once.... then same problem...

**Comment by psychomad** [comment]
I tried also as sudo user... and seem work. At least h asked me yes or not option.... then if i choose yes he give me "permission denied"
I think is not Belati issu but python bug... i will find out what's going on.. thanks for patience :)

**Comment by aancw** [comment]
Yes. I think the problem is in your python environment. Don't worry. I'm just make sure that my dep check is ok.
