### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Dmdv** [aancw/Belati#21]
Please provide the following details.

### Host System

- OS : Win 10
- Python version (`python --version`) : 2.7.14
- Pip version (`pip --version`) : 9.0.1
- Output of `pip freeze` :

**pip freeze:**

astroid==1.5.3
autopep8==1.3.3
backports.functools-lru-cache==1.4
click==6.7
colorama==0.3.9
configparser==3.5.0
enum34==1.1.6
Flask==0.12.2
Flask-WTF==0.14.2
isort==4.2.15
itsdangerous==0.24
Jinja2==2.9.6
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
pycodestyle==2.3.1
pylint==1.7.4
singledispatch==3.4.0.3
six==1.11.0
virtualenv==15.1.0
virtualenvwrapper-win==1.2.2
Werkzeug==0.12.2
wrapt==1.10.11
WTForms==2.1

### Error Description

Trying to invoke in the process of Belati installation I get this error:

e:\Development\Belati>pip install --upgrade --force-reinstall -r requirements.txt
Collecting dnspython (from -r requirements.txt (line 1))
  Using cached dnspython-1.15.0-py2.py3-none-any.whl
Collecting requests (from -r requirements.txt (line 2))
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting argparse (from -r requirements.txt (line 3))
  Using cached argparse-1.4.0-py2.py3-none-any.whl
Collecting texttable (from -r requirements.txt (line 4))
  Using cached texttable-1.1.1.tar.gz
Collecting python-geoip-geolite2 (from -r requirements.txt (line 5))
  Using cached python_geoip_geolite2-2015.0303-py2-none-any.whl
Collecting python-geoip (from -r requirements.txt (line 6))
  Using cached python_geoip-1.2-py27-none-any.whl
Collecting dnsknife (from -r requirements.txt (line 7))
  Using cached dnsknife-0.11.tar.gz
Collecting termcolor (from -r requirements.txt (line 8))
  Using cached termcolor-1.1.0.tar.gz
Collecting colorama (from -r requirements.txt (line 9))
  Using cached colorama-0.3.9-py2.py3-none-any.whl
Collecting validators (from -r requirements.txt (line 10))
  Using cached validators-0.12.0.tar.gz
Collecting tqdm (from -r requirements.txt (line 11))
  Using cached tqdm-4.19.4-py2.py3-none-any.whl
Collecting tldextract (from -r requirements.txt (line 12))
  Using cached tldextract-2.2.0-py2.py3-none-any.whl
Collecting fake-useragent (from -r requirements.txt (line 13))
  Using cached fake-useragent-0.1.8.tar.gz
Collecting python-wappalyzer (from -r requirements.txt (line 14))
  Using cached python-Wappalyzer-0.2.2.tar.gz
Collecting future (from -r requirements.txt (line 15))
  Using cached future-0.16.0.tar.gz
Collecting beautifulsoup4 (from -r requirements.txt (line 16))
  Using cached beautifulsoup4-4.6.0-py2-none-any.whl
Collecting python-whois (from -r requirements.txt (line 17))
  Using cached python-whois-0.6.5.tar.gz
Collecting futures (from -r requirements.txt (line 18))
  Using cached futures-3.1.1-py2-none-any.whl
Collecting django (from -r requirements.txt (line 19))
  Using cached Django-1.11.7-py2.py3-none-any.whl
Collecting pyexifinfo (from -r requirements.txt (line 20))
  Using cached pyexifinfo-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\pyexifinfo.egg-info
    writing pip-egg-info\pyexifinfo.egg-info\PKG-INFO
    writing top-level names to pip-egg-info\pyexifinfo.egg-info\top_level.txt
    writing dependency_links to pip-egg-info\pyexifinfo.egg-info\dependency_links.txt
    writing manifest file 'pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    writing manifest file 'pip-egg-info\pyexifinfo.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\aace~1\appdata\local\temp\pip-build-ybqwiq\pyexifinfo\setup.py", line 95, in <module>
        result = check_if_exiftool_is_already_installed()
      File "c:\users\aace~1\appdata\local\temp\pip-build-ybqwiq\pyexifinfo\setup.py", line 51, in check_if_exiftool_is_already_installed
        stderr = fnull
      File "c:\python27\lib\subprocess.py", line 168, in call
        return Popen(*popenargs, **kwargs).wait()
      File "c:\python27\lib\subprocess.py", line 390, in __init__
        errread, errwrite)
      File "c:\python27\lib\subprocess.py", line 640, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\aace~1\appdata\local\temp\pip-build-ybqwiq\pyexifinfo\

**Comment by aancw** [comment]
Some of python library that belati use is need exiftool binary. Please make sure that you already installed that :)
