### ISSUE TITLE
Error "you are missing a module required for Belati"

### ISSUE THREAD

**Issue by cegi** [aancw/Belati#25]
Please provide the following details.

### Host System

- OS : **4.14.0-kali1-amd64 #1 SMP Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux**
- Python version (`python --version`) : **Python 2.7.14**
- Pip version (`pip --version`) : **pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)**
- Output of `pip freeze` : [Upload the output to GitHub gists and provide link]

### Error Description

I launch "python2 Belati.py" and i get : 

**You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install --upgrade --force-reinstall -r requirements.txt`

            or manually install missing modules with:

            `pip install --upgrade --force-reinstall texttable python-geoip-geolite2 python-geoip dnsknife validators python-wappalyzer django pyexifinfo cmd2**

I already did all the steps above, the error persist. i managed to make it work before it just started recently to give that error, i get errors when trying to install the dependencies, has to do with Django : 

**Collecting django (from -r requirements.txt (line 19))
  Using cached Django-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-U2JmKn/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-U2JmKn/django/**

Thanks for the tool, would greatly appreciate if i can get help on this. Also got same error on ParrotSec OS

**Comment by tr0esmad** [comment]
Same problem here. Was able to work it around by pip installing a previous version of Django (1.11.8). Once installed, remove the django line from requirements.txt. 

BTW, remember to apt-get install exiftool first!

**Comment by aancw** [comment]
Reference to this PR:
https://github.com/aancw/Belati/pull/26
