### ISSUE TITLE
Docker install error 

### ISSUE THREAD

**Issue by Hax0rG1rl** [aancw/Belati#27]
Please provide the following details.

### Host System

- OS : Ubuntu Server 16.04

### Error Description while docker build -t belati .

Collecting django (from -r requirements.txt (line 19))
  Downloading Django-2.0.tar.gz (8.0MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3QsDJK/django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-3QsDJK/django/
The command '/bin/sh -c cd /home     && apt-get update     && apt-get install -y git python python-pip nmap exiftool     && git clone --branch v0.2.3-dev https://github.com/aancw/Belati.git     && cd Belati     && git submodule update --init --recursive --remote     && pip install --upgrade --force-reinstall -r requirements.txt     && echo 'alias belati="python /home/Belati/Belati.py"' >> ~/.bashrc' returned a non-zero code: 1

Please advise. 

Thanks!

**Comment by aancw** [comment]
Hi,

Reference to this issue https://github.com/aancw/Belati/issues/25 and this PR https://github.com/aancw/Belati/pull/26 . You need to specify Django version in requirement.txt:

Django==1.11.6

I will include this fix in 0.2.4

Thanks!

**Comment by Hax0rG1rl** [comment]
Thanks! I will wait for the change to be pulled. I can't do it by myself because of the way of how docker works.

**Comment by irwandi** [comment]
lru_cache only available on python 3 And Start using in django is v.2.0 ( CMIIW )
ref. https://docs.djangoproject.com/en/2.0/releases/1.7/#django-utils-functional-memoize-function

To Fix This, use Django==1.11.6 in Requirement.txt
