### ISSUE TITLE
No such file or directory: '/usr/local/man/man1

### ISSUE THREAD

**Issue by maurilee** [aancw/Belati#28]
Please provide the following details.

### Host System

- OS :Kali Linux 2017 2
- Python version (`python --version`) :Python 2.7.14+
- Pip version (`pip --version`) :pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
- Output of `pip freeze` : [Upload the output to GitHub gists and provide link]

### Error Description
I have missing a module error then with suggested command "pip install --upgrade --force-reinstall -r requirements.txt"
this is the output:
"
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 377, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: '/usr/local/man/man1'

Tnks for support 
M

**Comment by aancw** [comment]
Do you have man package for your distro? Or have you deleted your man dir?

**Comment by maurilee** [comment]
This is my manpath output:
/usr/local/man:/usr/local/share/man:/usr/share/man
In /usr/local/man/man1 there is only tqdm.1 file, in fact error appears just after tqdm uninstallation message: 
.......
 Found existing installation: validators 0.12.0
    Uninstalling validators-0.12.0:
      Successfully uninstalled validators-0.12.0
  Found existing installation: tqdm 4.19.5
    Uninstalling tqdm-4.19.5:
      Successfully uninstalled tqdm-4.19.5
  Rolling back uninstall of tqdm

**Comment by maurilee** [comment]
manually removed file tqdm.1, run again " pip install --upgrade --force-reinstall -r requirements.txt", this time it works fine.
But when I try to start Belati (python Belati.py).... same message:

"            You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install --upgrade --force-reinstall -r requirements.txt`

            or manually install missing modules with:

            `pip install --upgrade --force-reinstall Django==1.11.6`
"

**Comment by aancw** [comment]
Nah, you are missing one lib. Please install with:

pip install --upgrade --force-reinstall Django==1.11.6

**Comment by maurilee** [comment]
It seems Django problems but this is install output:
..... Successfully installed BeautifulSoup-3.2.1 Django-1.11.6.......

**Comment by aancw** [comment]
Please close this issue if your problem is fixed

**Comment by maurilee** [comment]
root@kali:/opt/belati/Belati# pip install --upgrade --force-reinstall Django==1.11.6
Collecting Django==1.11.6
  Using cached Django-1.11.6-py2.py3-none-any.whl
Collecting pytz (from Django==1.11.6)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Installing collected packages: pytz, Django
  Found existing installation: pytz 2017.3
    Uninstalling pytz-2017.3:
      Successfully uninstalled pytz-2017.3
  Found existing installation: Django 1.11.6
    Uninstalling Django-1.11.6:
      Successfully uninstalled Django-1.11.6
Successfully installed Django-1.11.6 pytz-2017.3

.... same error
You are missing a module required for Belati. In order to continue using Belati, please install them with:

            `pip install --upgrade --force-reinstall -r requirements.txt`

            or manually install missing modules with:

            `pip install --upgrade --force-reinstall Django==1.11.6`

**Comment by hpiedcoq** [comment]
same here.

**Comment by aancw** [comment]
How about installing Django without version?

Pip install Django

**Comment by aancw** [comment]
Let know if that works.

**Comment by aancw** [comment]
Ah i see. Please remove version from requirement.txt, i need to fix this parser.

**Comment by aancw** [comment]
Please git pull and then pip install -r requirements.txt again

Thanks!

**Comment by hpiedcoq** [comment]
`Collecting Django==2.0
  Downloading Django-2.0.tar.gz (8.0MB)
    100% |████████████████████████████████| 8.0MB 65kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-WrOsmw/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
`

**Comment by aancw** [comment]
For temporary fix, install django==1.11.6 but requirements.txt still using Django.

**Comment by aancw** [comment]
I'm on mobile. I will try to fix that issue by tomorrow

**Comment by aancw** [comment]
Reference to this PR https://github.com/aancw/Belati/pull/26

**Comment by maurilee** [comment]
Removed version from requirements. It works!

Thanks!
