### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

### ISSUE THREAD

**Issue by hellochunqiu** [aancw/Belati#29]
Please provide the following details.

### Host System

- OS :kali 2
- Python version (`python --2.7`) :
- Pip version (`pip --10.0.1`) :
- Output of `pip freeze` : [Upload the output to GitHub gists and provide link]

### Error Description

Please provide the details of the error. Try to provide the **output** and also **steps to reproduce** if required.

hello,I encountered such a problem with "virtualenv"：
source belati/bin/activate 
pip install -r requirements.txt
python Belati.py 

Traceback (most recent call last):
  File "Belati.py", line 38, in <module>
    from plugins.banner_grab import BannerGrab
  File "/Belati/plugins/banner_grab.py", line 24, in <module>
    from url_request import URLRequest
  File "/Belati/plugins/url_request.py", line 26, in <module>
    from user_agents import UserAgents
  File "/Belati/plugins/user_agents.py", line 25, in <module>
    ua = UserAgent()
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/fake.py", line 69, in __init__
    self.load()
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/fake.py", line 78, in load
    verify_ssl=self.verify_ssl,
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 252, in load_cached
    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 247, in update
    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 189, in load
    verify_ssl=verify_ssl,
  File "/Belati/belati/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached

I tried some methods, but I didn't succeed.

@aancw @Chan9390 @ElectricCaffeine

**Comment by aancw** [comment]
Just try again and see if that fixed the problem.
`Maximum amount of retries reached`

**Comment by hellochunqiu** [comment]
No. the same result, should I delete "virtualenv"? From the new arrangement

**Comment by aancw** [comment]
Reference to this issue https://github.com/hellysmile/fake-useragent/issues/53
Make sure you have openssl and no ssl problem as mentioned on that issue.

**Comment by hellochunqiu** [comment]
ImportError: cannot import name UserAgent

**Comment by hellochunqiu** [comment]
I already have "pip install useragent"

**Comment by WichitaLifeICT** [comment]
@aancw @hellysmile which file do you address the ssl certs in? 


‘’’python
from fake_useragent import UserAgent
ua = UserAgent(verify_ssl=False)
‘’’

**Comment by aancw** [comment]
Maybe this problem occurred because i'm not using verify_ssl=False

**Comment by hellochunqiu** [comment]
Yes, you are right. My problem is that he will automatically upgrade to "pip-10" after using "virtualenv". It is wrong and incompatible. By breaking the net to work in "pip-9", these problems can be solved, thank you.

**Comment by aancw** [comment]
But, if you are using verify_ssl=false at user_agents.py, it still not working?

**Comment by hellochunqiu** [comment]
Did you install "Libcurl14-openssl-dev" when installing dependency?

**Comment by aancw** [comment]
I'm using ArchLinux btw

**Comment by hellochunqiu** [comment]
OK, the problem is solved. This is caused by the problem of dependence and the latest environmental problems of "Python". To install dependencies and reduce versions, "pip10" is not compatible.

At the same time, I think many beginners do not understand "dependence", but grow up in solving problems.

Fortunately, there are "Google" and "you" and "everyone".

**Comment by hellochunqiu** [comment]
And happy to know you

**Comment by aancw** [comment]
Happy to know you too. If you have any question, feel free to open issue. Pull request is welcome ❤️

**Comment by hellochunqiu** [comment]
Thank you

**Comment by ryanbrewster124** [comment]
has anyone found a solution to this??
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries

**Comment by ryanbrewster124** [comment]
ok this fixed it for me:
pip install fake-useragent --upgrade

**Comment by hellysmile** [comment]
hey there, `pip install -U fake-useragent` should fix issue

**Comment by aancw** [comment]
@ryanbrewster124 If you encounter this problem again, please be patient to wait for queue. I think fakeuseragent limiting request from per IP.

**Comment by impankajnegi** [comment]
Please check if u have a fast internet

**Comment by Foreveri02** [comment]
> hey there, `pip install -U fake-useragent` should fix issue

thanks bro
