### ISSUE TITLE
no such table 'projects'

### ISSUE THREAD

**Issue by maldevel** [aancw/Belati#5]
Hi there,
A table seems that is missing from sqlite db.
```
File "Belati.py", line 403, in <module>
    BelatiApp = Belati()
  File "Belati.py", line 101, in __init__
    self.project_id = self.db.create_new_project(domain, orgcomp, datetime.datetime.now())
  File "/path/to/Belati/plugins/database.py", line 50, in create_new_project
    cur.execute("INSERT INTO projects(`project_domain`, `project_org`, `started_time`) VALUES (?, ?, ?)", (project_domain, project_org, time))
sqlite3.OperationalError: no such table: projects
```

**Comment by aancw** [comment]
Hi, can i see your belati.conf?

Table `projects` is exist in belati.db file. To be make sure, i'm using belati.db from repository
![sqlite-belati](https://user-images.githubusercontent.com/6284204/27071241-435c5cde-5046-11e7-9d83-c1c196a4a6a0.png)

**Comment by aancw** [comment]
Fresh install

![belati-projects-testing](https://user-images.githubusercontent.com/6284204/27071418-1811592a-5047-11e7-8253-64181f54c638.png)

**Comment by maldevel** [comment]
works like charm, didnt notice .conf file :D

**Comment by aancw** [comment]
FYI, in the next release i will use auto configuration. Because belati will use Django database for storing information.

Thanks!
