### ISSUE TITLE
its possible for working on maltego 

### ISSUE THREAD

**Issue by glerinsonum** [aancw/Belati#6]

**Comment by aancw** [comment]
I've planning to implement this in future. If you have any reference, please drop link here :)

@glerinsonum

**Comment by glerinsonum** [comment]
@aancw Thanks to your grace, brother, thats you havs offereds this OSINT Project for Windows
Please. Integrates and Pipl.com service, for collecting data of person.

**Learns hows you cans integrates your file project from your web server using query link**
1 [``](https://www.youtube.com/watch?v=IpqVUcW4YqU)
3 Downloads in your pc this  PHP Service Pipl, because is necessary
[https://github.com/piplcom/piplapis-php](url)
4 Developes some objectives with using SubLimeText2
Example. ToPersonName. ToEmailAddress.ToPlaces.ToLocation.Etc.etc. For Maltego. 
6 eBook [https://pipl.com/api/guide/introduction](url) [http://pipl.com/api/reference/](url) 
**There are with some versions **
[https://github.com/piplcom/piplapis-python](url)
[https://github.com/piplcom/piplapis-ruby](url)
[https://github.com/piplcom/piplapis-java](url)
6 Uploads to your web server PHP Pipl Libraries with your files thats are in a folder, like transforms
7 Create an account to [http://cetas.paterva.com/TDS/](url)
8 Create seeds
9 Create transforms names by decide your query link script
10 https://docs.paterva.com/en/developer-portal/transform_libraries/ without API 
![1](https://user-images.githubusercontent.com/21057103/27324767-0ef35c44-555b-11e7-9d43-98bc069bb97e.GIF)
![2](https://user-images.githubusercontent.com/21057103/27324768-0f2d174a-555b-11e7-85b2-02ad300d584a.png)

![3](https://user-images.githubusercontent.com/21057103/27326377-22384288-5560-11e7-8ce0-a803454a31b7.png)
![4](https://user-images.githubusercontent.com/21057103/27326378-224609fe-5560-11e7-8e5f-50f1e1634ce8.png)
TYPOLOGY - STRUCTURE 
![gweg](https://user-images.githubusercontent.com/21057103/27327573-d1b5958c-5563-11e7-9879-20a823c26845.png)

There are full tools 
https://github.com/jmortega/osint_tools_security_auditing

CONTACT ME: facebook.com/fravetto.naan

**Comment by aancw** [comment]
@glerinsonum Thanks for your reference. I will consider this for future development. If you are using windows, this project is working fine :)

**Comment by glerinsonum** [comment]
@aancw :)

**Comment by glerinsonum** [comment]
I'm not developer for python or PHP. Contact me at facebook.com/fravetto.naan

**Comment by aancw** [comment]
Oh i see. Do you have Telegram, Gentian?

**Comment by glerinsonum** [comment]
I have whatsapp :) 

+355665270055

**Comment by glerinsonum** [comment]
@aancw You probably you can make a partner with company maltego, with the aim, that the people, whens install your plugin in the Maltego Classic, will be interested to your website, or to your email address, for a key, when the user pay for this key, and puts the key to Maltego GUI Client, the user will use all transforms for your entities. 

So. I would like to collaborate with you.

![1](https://user-images.githubusercontent.com/21057103/27351159-46b41c1c-55b1-11e7-806c-caad4f670edf.png)
![2](https://user-images.githubusercontent.com/21057103/27351162-46b79df6-55b1-11e7-9568-3e3095ab90f4.png)
![3](https://user-images.githubusercontent.com/21057103/27351160-46b46c4e-55b1-11e7-96b1-b15b548c0ff7.png)
![4](https://user-images.githubusercontent.com/21057103/27351161-46b503e8-55b1-11e7-9339-e16919ad601d.png)
![5](https://user-images.githubusercontent.com/21057103/27351163-46b85480-55b1-11e7-9e53-04ac81852ceb.png)
![6](https://user-images.githubusercontent.com/21057103/27351158-46b35a0c-55b1-11e7-921a-56ee36e6c4a4.png)

Calling for Remote Scripting from Maltego GUI Client to iTDS your account to your Web Server CGI
[https://www.youtube.com/watch?v=4KvVmdely6k](url)
![7](https://user-images.githubusercontent.com/21057103/27351236-813f7c0a-55b1-11e7-8978-d35e0ae7a062.png)
When the user at Maltego GUI call an transform for Input.Entity.PersonName
There said. to PHP Script AddEntity. Significat, When user calls this request, give this response "Example" returns response in another entity "Tophrase" To.emailaddresses. etc etc.
[https://www.youtube.com/watch?v=XR6Sxe3wlDE](url)
So the communicate, the communication proceeds in two ways
from your web server with PHP APIs & and from your web server CGI with remote scripting.

**Comment by glerinsonum** [comment]
![1](https://user-images.githubusercontent.com/21057103/27353195-09b1102a-55b8-11e7-82d6-c46435c11845.GIF)

You cans returns this request to PhraseNotes Entity :) using CGI Remote Scripting to Web Server, or PHP
Input.Domain
Output.Phrase
http://docs.paterva.com/

:)

**Comment by glerinsonum** [comment]
@aancw you cans creates the entities at maltegoCE.  :) 
Take a look this photo. Beatiful OSINTs with exploring Maltego
![1](https://user-images.githubusercontent.com/21057103/27354027-0aa156a4-55bb-11e7-992c-ceef4ec9a9ef.jpg)

**Comment by glerinsonum** [comment]
@aancw Don't missing. lose these scripts. 

[https://github.com/jmortega/osint_tools_security_auditing](url)
Create entities from MaltegoCE for OSINTs of JMortega & Betali. 
Example. If in your CLI said: example. 
enter the link of account twitter for getting gps cordinates of photo. 
Create an Entity Twitter. 
And your transform from python scripts will returns in another entity
like this. 

![2](https://user-images.githubusercontent.com/21057103/27354233-bd95369a-55bb-11e7-8f7a-275cbe1aa92d.GIF)
![3](https://user-images.githubusercontent.com/21057103/27354234-bd961cea-55bb-11e7-8416-ed595c8d8434.GIF)
Learns from [https://docs.paterva.com//en/entity-guide/standard_entities/locations/GPS/](url)
[https://docs.paterva.com/en/](url)

I'm not a developer. :( 
i'm a proponent, reasoner, analyser, counciler in the OSINT  project.

**Comment by glerinsonum** [comment]
@aancw I woulds likes to works with you with the aim for to have you and I an public plugin with our OSINT. :)

**Comment by glerinsonum** [comment]
![dg](https://user-images.githubusercontent.com/21057103/27359478-d2b00e0a-55d0-11e7-8d43-365fffaadbf2.png)

You cans be an partnership with Paterva Company of Maltego, likes others the companies. 
And. Whens you finisheds with the Project OSINT into Maltego. Opens an website, with the aim thats the users will contacts you per paym for an key, to use your transforms OSINT for entities project at Maltego by iTDS Server.

And. You personally. Cans developes and cans use your Project OSINT and with python at home. 
Finishs the project OSINT with local transforms at python codes for the entities Maltego, and contacts me, to see the your project osint with Maltego. 
I'm a proponent for you. :)

**Comment by glerinsonum** [comment]
@aancw [https://www.paterva.com/web7/docs/userguides/user_guide.php](url)

**Comment by aancw** [comment]
@glerinsonum Thanks for your awesome suggest and reference. I need time to learn about that first :)

You can contact my email address for detail about your suggestion. Maybe we can talk about this privately :)
My email : cacaddv@gmail.com

**Comment by glerinsonum** [comment]
@aancw [https://i.imgur.com/yqFpAAJ.png](url)

**Comment by glerinsonum** [comment]
![ter](https://user-images.githubusercontent.com/21057103/27375278-82c81ce0-5623-11e7-8be6-12a3c9eac011.png)

**Comment by glerinsonum** [comment]
@aancw I have sends a message to Hangout :)

**Comment by aancw** [comment]
I will close this issue. Thanks!
